url=jdbc:mysql://localhost:3306/liquibase_db?useSSL=false&allowPublicKeyRetrieval=true
username=root
password=Apana@123456
driver=com.mysql.cj.jdbc.Driver
changeLogFile=changelog/db.changelog-master.xml
logLevel=INFO
logFile=liquibase-run.log
classpath=/home/intern/.local/share/DBeaverData/drivers/maven/maven-central/com.mysql/mysql-connector-j-8.2.0.jar
